GET http://localhost:5000/api/v1/user/fdsfsdfs


###
POST http://localhost:5000/api/v1/auth/register
Content-Type: application/json

{
    "email": "hothanhnam@gmail.com",
    "password": "nam1234"
}

###
POST http://localhost:5000/api/v1/auth/login
Content-Type: application/json

{
    "email": "hothanhnam@gmail.com",
    "password": "nam1234"
}

